/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen.tables.records;


import dev.kamko.jooq_gen.tables.Article;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record9<Long, String, String, String, String, Timestamp, Long, String, JSONB> {

    private static final long serialVersionUID = 940561398;

    /**
     * Setter for <code>public.article.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.article.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article.perex</code>.
     */
    public void setPerex(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article.perex</code>.
     */
    public String getPerex() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.article.body</code>.
     */
    public void setBody(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.article.body</code>.
     */
    public String getBody() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.article.published_at</code>.
     */
    public void setPublishedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.article.published_at</code>.
     */
    public Timestamp getPublishedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.article.source_id</code>.
     */
    public void setSourceId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.article.source_id</code>.
     */
    public Long getSourceId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.article.category</code>.
     */
    public void setCategory(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.article.category</code>.
     */
    public String getCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.article.other_info</code>.
     */
    public void setOtherInfo(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.article.other_info</code>.
     */
    public JSONB getOtherInfo() {
        return (JSONB) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, Timestamp, Long, String, JSONB> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, Timestamp, Long, String, JSONB> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Article.ARTICLE.ID;
    }

    @Override
    public Field<String> field2() {
        return Article.ARTICLE.URL;
    }

    @Override
    public Field<String> field3() {
        return Article.ARTICLE.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Article.ARTICLE.PEREX;
    }

    @Override
    public Field<String> field5() {
        return Article.ARTICLE.BODY;
    }

    @Override
    public Field<Timestamp> field6() {
        return Article.ARTICLE.PUBLISHED_AT;
    }

    @Override
    public Field<Long> field7() {
        return Article.ARTICLE.SOURCE_ID;
    }

    @Override
    public Field<String> field8() {
        return Article.ARTICLE.CATEGORY;
    }

    @Override
    public Field<JSONB> field9() {
        return Article.ARTICLE.OTHER_INFO;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getPerex();
    }

    @Override
    public String component5() {
        return getBody();
    }

    @Override
    public Timestamp component6() {
        return getPublishedAt();
    }

    @Override
    public Long component7() {
        return getSourceId();
    }

    @Override
    public String component8() {
        return getCategory();
    }

    @Override
    public JSONB component9() {
        return getOtherInfo();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getPerex();
    }

    @Override
    public String value5() {
        return getBody();
    }

    @Override
    public Timestamp value6() {
        return getPublishedAt();
    }

    @Override
    public Long value7() {
        return getSourceId();
    }

    @Override
    public String value8() {
        return getCategory();
    }

    @Override
    public JSONB value9() {
        return getOtherInfo();
    }

    @Override
    public ArticleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ArticleRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ArticleRecord value4(String value) {
        setPerex(value);
        return this;
    }

    @Override
    public ArticleRecord value5(String value) {
        setBody(value);
        return this;
    }

    @Override
    public ArticleRecord value6(Timestamp value) {
        setPublishedAt(value);
        return this;
    }

    @Override
    public ArticleRecord value7(Long value) {
        setSourceId(value);
        return this;
    }

    @Override
    public ArticleRecord value8(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ArticleRecord value9(JSONB value) {
        setOtherInfo(value);
        return this;
    }

    @Override
    public ArticleRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6, Long value7, String value8, JSONB value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Long id, String url, String title, String perex, String body, Timestamp publishedAt, Long sourceId, String category, JSONB otherInfo) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, url);
        set(2, title);
        set(3, perex);
        set(4, body);
        set(5, publishedAt);
        set(6, sourceId);
        set(7, category);
        set(8, otherInfo);
    }
}
