/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen.tables.records;


import dev.kamko.jooq_gen.tables.ArticleFbEngagement;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFbEngagementRecord extends UpdatableRecordImpl<ArticleFbEngagementRecord> implements Record7<String, Integer, Integer, Integer, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -1421169219;

    /**
     * Setter for <code>public.article_fb_engagement.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.article_fb_engagement.reaction_count</code>.
     */
    public void setReactionCount(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.reaction_count</code>.
     */
    public Integer getReactionCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.article_fb_engagement.comment_count</code>.
     */
    public void setCommentCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.comment_count</code>.
     */
    public Integer getCommentCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.article_fb_engagement.share_count</code>.
     */
    public void setShareCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.share_count</code>.
     */
    public Integer getShareCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.article_fb_engagement.comment_plugin_count</code>.
     */
    public void setCommentPluginCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.comment_plugin_count</code>.
     */
    public Integer getCommentPluginCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.article_fb_engagement.sync_date</code>.
     */
    public void setSyncDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.sync_date</code>.
     */
    public Timestamp getSyncDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.article_fb_engagement.id</code>.
     */
    public void setId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.article_fb_engagement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, Integer, Integer, Integer, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, Integer, Integer, Integer, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.URL;
    }

    @Override
    public Field<Integer> field2() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.REACTION_COUNT;
    }

    @Override
    public Field<Integer> field3() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.COMMENT_COUNT;
    }

    @Override
    public Field<Integer> field4() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.SHARE_COUNT;
    }

    @Override
    public Field<Integer> field5() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.COMMENT_PLUGIN_COUNT;
    }

    @Override
    public Field<Timestamp> field6() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.SYNC_DATE;
    }

    @Override
    public Field<Integer> field7() {
        return ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.ID;
    }

    @Override
    public String component1() {
        return getUrl();
    }

    @Override
    public Integer component2() {
        return getReactionCount();
    }

    @Override
    public Integer component3() {
        return getCommentCount();
    }

    @Override
    public Integer component4() {
        return getShareCount();
    }

    @Override
    public Integer component5() {
        return getCommentPluginCount();
    }

    @Override
    public Timestamp component6() {
        return getSyncDate();
    }

    @Override
    public Integer component7() {
        return getId();
    }

    @Override
    public String value1() {
        return getUrl();
    }

    @Override
    public Integer value2() {
        return getReactionCount();
    }

    @Override
    public Integer value3() {
        return getCommentCount();
    }

    @Override
    public Integer value4() {
        return getShareCount();
    }

    @Override
    public Integer value5() {
        return getCommentPluginCount();
    }

    @Override
    public Timestamp value6() {
        return getSyncDate();
    }

    @Override
    public Integer value7() {
        return getId();
    }

    @Override
    public ArticleFbEngagementRecord value1(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value2(Integer value) {
        setReactionCount(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value3(Integer value) {
        setCommentCount(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value4(Integer value) {
        setShareCount(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value5(Integer value) {
        setCommentPluginCount(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value6(Timestamp value) {
        setSyncDate(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord value7(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleFbEngagementRecord values(String value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleFbEngagementRecord
     */
    public ArticleFbEngagementRecord() {
        super(ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT);
    }

    /**
     * Create a detached, initialised ArticleFbEngagementRecord
     */
    public ArticleFbEngagementRecord(String url, Integer reactionCount, Integer commentCount, Integer shareCount, Integer commentPluginCount, Timestamp syncDate, Integer id) {
        super(ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT);

        set(0, url);
        set(1, reactionCount);
        set(2, commentCount);
        set(3, shareCount);
        set(4, commentPluginCount);
        set(5, syncDate);
        set(6, id);
    }
}
