/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen.tables.records;


import dev.kamko.jooq_gen.tables.MonitoredArticle;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MonitoredArticleRecord extends UpdatableRecordImpl<MonitoredArticleRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1610145954;

    /**
     * Setter for <code>public.monitored_article.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.monitored_article.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.monitored_article.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.monitored_article.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MonitoredArticle.MONITORED_ARTICLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return MonitoredArticle.MONITORED_ARTICLE.ARTICLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getArticleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getArticleId();
    }

    @Override
    public MonitoredArticleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MonitoredArticleRecord value2(Long value) {
        setArticleId(value);
        return this;
    }

    @Override
    public MonitoredArticleRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonitoredArticleRecord
     */
    public MonitoredArticleRecord() {
        super(MonitoredArticle.MONITORED_ARTICLE);
    }

    /**
     * Create a detached, initialised MonitoredArticleRecord
     */
    public MonitoredArticleRecord(Long id, Long articleId) {
        super(MonitoredArticle.MONITORED_ARTICLE);

        set(0, id);
        set(1, articleId);
    }
}
