/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen;


import dev.kamko.jooq_gen.tables.Article;
import dev.kamko.jooq_gen.tables.ArticleFbEngagement;
import dev.kamko.jooq_gen.tables.Media;
import dev.kamko.jooq_gen.tables.MonitorJobRunLog;
import dev.kamko.jooq_gen.tables.MonitoredArticle;
import dev.kamko.jooq_gen.tables.Source;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_PKEY = Indexes0.ARTICLE_PKEY;
    public static final Index ARTICLE_URL_UINDEX = Indexes0.ARTICLE_URL_UINDEX;
    public static final Index ARTICLE_FB_ENGAGEMENT_PKEY = Indexes0.ARTICLE_FB_ENGAGEMENT_PKEY;
    public static final Index ARTICLE_FB_ENGAGEMENT_URL_INDEX = Indexes0.ARTICLE_FB_ENGAGEMENT_URL_INDEX;
    public static final Index MEDIA_PKEY = Indexes0.MEDIA_PKEY;
    public static final Index MONITOR_JOB_RUN_LOG_PKEY = Indexes0.MONITOR_JOB_RUN_LOG_PKEY;
    public static final Index MONITORED_ARTICLE_PKEY = Indexes0.MONITORED_ARTICLE_PKEY;
    public static final Index SOURCE_PKEY = Indexes0.SOURCE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARTICLE_PKEY = Internal.createIndex("article_pkey", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
        public static Index ARTICLE_URL_UINDEX = Internal.createIndex("article_url_uindex", Article.ARTICLE, new OrderField[] { Article.ARTICLE.URL }, true);
        public static Index ARTICLE_FB_ENGAGEMENT_PKEY = Internal.createIndex("article_fb_engagement_pkey", ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT, new OrderField[] { ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.ID }, true);
        public static Index ARTICLE_FB_ENGAGEMENT_URL_INDEX = Internal.createIndex("article_fb_engagement_url_index", ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT, new OrderField[] { ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.URL }, false);
        public static Index MEDIA_PKEY = Internal.createIndex("media_pkey", Media.MEDIA, new OrderField[] { Media.MEDIA.ID }, true);
        public static Index MONITOR_JOB_RUN_LOG_PKEY = Internal.createIndex("monitor_job_run_log_pkey", MonitorJobRunLog.MONITOR_JOB_RUN_LOG, new OrderField[] { MonitorJobRunLog.MONITOR_JOB_RUN_LOG.ID }, true);
        public static Index MONITORED_ARTICLE_PKEY = Internal.createIndex("monitored_article_pkey", MonitoredArticle.MONITORED_ARTICLE, new OrderField[] { MonitoredArticle.MONITORED_ARTICLE.ID }, true);
        public static Index SOURCE_PKEY = Internal.createIndex("source_pkey", Source.SOURCE, new OrderField[] { Source.SOURCE.ID }, true);
    }
}
