/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen;


import dev.kamko.jooq_gen.tables.Article;
import dev.kamko.jooq_gen.tables.ArticleFbEngagement;
import dev.kamko.jooq_gen.tables.ArticleMedia;
import dev.kamko.jooq_gen.tables.Media;
import dev.kamko.jooq_gen.tables.MonitorJobRunLog;
import dev.kamko.jooq_gen.tables.MonitoredArticle;
import dev.kamko.jooq_gen.tables.Source;
import dev.kamko.jooq_gen.tables.records.ArticleFbEngagementRecord;
import dev.kamko.jooq_gen.tables.records.ArticleMediaRecord;
import dev.kamko.jooq_gen.tables.records.ArticleRecord;
import dev.kamko.jooq_gen.tables.records.MediaRecord;
import dev.kamko.jooq_gen.tables.records.MonitorJobRunLogRecord;
import dev.kamko.jooq_gen.tables.records.MonitoredArticleRecord;
import dev.kamko.jooq_gen.tables.records.SourceRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ArticleRecord, Long> IDENTITY_ARTICLE = Identities0.IDENTITY_ARTICLE;
    public static final Identity<ArticleFbEngagementRecord, Integer> IDENTITY_ARTICLE_FB_ENGAGEMENT = Identities0.IDENTITY_ARTICLE_FB_ENGAGEMENT;
    public static final Identity<MediaRecord, Long> IDENTITY_MEDIA = Identities0.IDENTITY_MEDIA;
    public static final Identity<MonitorJobRunLogRecord, Long> IDENTITY_MONITOR_JOB_RUN_LOG = Identities0.IDENTITY_MONITOR_JOB_RUN_LOG;
    public static final Identity<MonitoredArticleRecord, Long> IDENTITY_MONITORED_ARTICLE = Identities0.IDENTITY_MONITORED_ARTICLE;
    public static final Identity<SourceRecord, Long> IDENTITY_SOURCE = Identities0.IDENTITY_SOURCE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArticleRecord> ARTICLE_PKEY = UniqueKeys0.ARTICLE_PKEY;
    public static final UniqueKey<ArticleFbEngagementRecord> ARTICLE_FB_ENGAGEMENT_PKEY = UniqueKeys0.ARTICLE_FB_ENGAGEMENT_PKEY;
    public static final UniqueKey<MediaRecord> MEDIA_PKEY = UniqueKeys0.MEDIA_PKEY;
    public static final UniqueKey<MonitorJobRunLogRecord> MONITOR_JOB_RUN_LOG_PKEY = UniqueKeys0.MONITOR_JOB_RUN_LOG_PKEY;
    public static final UniqueKey<MonitoredArticleRecord> MONITORED_ARTICLE_PKEY = UniqueKeys0.MONITORED_ARTICLE_PKEY;
    public static final UniqueKey<SourceRecord> SOURCE_PKEY = UniqueKeys0.SOURCE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ArticleRecord, SourceRecord> ARTICLE__ARTICLE_SOURCE_ID_FKEY = ForeignKeys0.ARTICLE__ARTICLE_SOURCE_ID_FKEY;
    public static final ForeignKey<ArticleMediaRecord, ArticleRecord> ARTICLE_MEDIA__ARTICLE_MEDIA_ARTICLE_ID_FKEY = ForeignKeys0.ARTICLE_MEDIA__ARTICLE_MEDIA_ARTICLE_ID_FKEY;
    public static final ForeignKey<ArticleMediaRecord, MediaRecord> ARTICLE_MEDIA__ARTICLE_MEDIA_MEDIA_ID_FKEY = ForeignKeys0.ARTICLE_MEDIA__ARTICLE_MEDIA_MEDIA_ID_FKEY;
    public static final ForeignKey<MonitoredArticleRecord, ArticleRecord> MONITORED_ARTICLE__MONITORED_ARTICLE_ARTICLE_ID_FKEY = ForeignKeys0.MONITORED_ARTICLE__MONITORED_ARTICLE_ARTICLE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ArticleRecord, Long> IDENTITY_ARTICLE = Internal.createIdentity(Article.ARTICLE, Article.ARTICLE.ID);
        public static Identity<ArticleFbEngagementRecord, Integer> IDENTITY_ARTICLE_FB_ENGAGEMENT = Internal.createIdentity(ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT, ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.ID);
        public static Identity<MediaRecord, Long> IDENTITY_MEDIA = Internal.createIdentity(Media.MEDIA, Media.MEDIA.ID);
        public static Identity<MonitorJobRunLogRecord, Long> IDENTITY_MONITOR_JOB_RUN_LOG = Internal.createIdentity(MonitorJobRunLog.MONITOR_JOB_RUN_LOG, MonitorJobRunLog.MONITOR_JOB_RUN_LOG.ID);
        public static Identity<MonitoredArticleRecord, Long> IDENTITY_MONITORED_ARTICLE = Internal.createIdentity(MonitoredArticle.MONITORED_ARTICLE, MonitoredArticle.MONITORED_ARTICLE.ID);
        public static Identity<SourceRecord, Long> IDENTITY_SOURCE = Internal.createIdentity(Source.SOURCE, Source.SOURCE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ArticleRecord> ARTICLE_PKEY = Internal.createUniqueKey(Article.ARTICLE, "article_pkey", Article.ARTICLE.ID);
        public static final UniqueKey<ArticleFbEngagementRecord> ARTICLE_FB_ENGAGEMENT_PKEY = Internal.createUniqueKey(ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT, "article_fb_engagement_pkey", ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT.ID);
        public static final UniqueKey<MediaRecord> MEDIA_PKEY = Internal.createUniqueKey(Media.MEDIA, "media_pkey", Media.MEDIA.ID);
        public static final UniqueKey<MonitorJobRunLogRecord> MONITOR_JOB_RUN_LOG_PKEY = Internal.createUniqueKey(MonitorJobRunLog.MONITOR_JOB_RUN_LOG, "monitor_job_run_log_pkey", MonitorJobRunLog.MONITOR_JOB_RUN_LOG.ID);
        public static final UniqueKey<MonitoredArticleRecord> MONITORED_ARTICLE_PKEY = Internal.createUniqueKey(MonitoredArticle.MONITORED_ARTICLE, "monitored_article_pkey", MonitoredArticle.MONITORED_ARTICLE.ID);
        public static final UniqueKey<SourceRecord> SOURCE_PKEY = Internal.createUniqueKey(Source.SOURCE, "source_pkey", Source.SOURCE.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ArticleRecord, SourceRecord> ARTICLE__ARTICLE_SOURCE_ID_FKEY = Internal.createForeignKey(dev.kamko.jooq_gen.Keys.SOURCE_PKEY, Article.ARTICLE, "article__article_source_id_fkey", Article.ARTICLE.SOURCE_ID);
        public static final ForeignKey<ArticleMediaRecord, ArticleRecord> ARTICLE_MEDIA__ARTICLE_MEDIA_ARTICLE_ID_FKEY = Internal.createForeignKey(dev.kamko.jooq_gen.Keys.ARTICLE_PKEY, ArticleMedia.ARTICLE_MEDIA, "article_media__article_media_article_id_fkey", ArticleMedia.ARTICLE_MEDIA.ARTICLE_ID);
        public static final ForeignKey<ArticleMediaRecord, MediaRecord> ARTICLE_MEDIA__ARTICLE_MEDIA_MEDIA_ID_FKEY = Internal.createForeignKey(dev.kamko.jooq_gen.Keys.MEDIA_PKEY, ArticleMedia.ARTICLE_MEDIA, "article_media__article_media_media_id_fkey", ArticleMedia.ARTICLE_MEDIA.MEDIA_ID);
        public static final ForeignKey<MonitoredArticleRecord, ArticleRecord> MONITORED_ARTICLE__MONITORED_ARTICLE_ARTICLE_ID_FKEY = Internal.createForeignKey(dev.kamko.jooq_gen.Keys.ARTICLE_PKEY, MonitoredArticle.MONITORED_ARTICLE, "monitored_article__monitored_article_article_id_fkey", MonitoredArticle.MONITORED_ARTICLE.ARTICLE_ID);
    }
}
