/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen;


import dev.kamko.jooq_gen.tables.Article;
import dev.kamko.jooq_gen.tables.ArticleFbEngagement;
import dev.kamko.jooq_gen.tables.ArticleMedia;
import dev.kamko.jooq_gen.tables.Media;
import dev.kamko.jooq_gen.tables.MonitorJobRunLog;
import dev.kamko.jooq_gen.tables.MonitoredArticle;
import dev.kamko.jooq_gen.tables.Source;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1650318663;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.article</code>.
     */
    public final Article ARTICLE = dev.kamko.jooq_gen.tables.Article.ARTICLE;

    /**
     * The table <code>public.article_fb_engagement</code>.
     */
    public final ArticleFbEngagement ARTICLE_FB_ENGAGEMENT = dev.kamko.jooq_gen.tables.ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT;

    /**
     * The table <code>public.article_media</code>.
     */
    public final ArticleMedia ARTICLE_MEDIA = dev.kamko.jooq_gen.tables.ArticleMedia.ARTICLE_MEDIA;

    /**
     * The table <code>public.media</code>.
     */
    public final Media MEDIA = dev.kamko.jooq_gen.tables.Media.MEDIA;

    /**
     * The table <code>public.monitor_job_run_log</code>.
     */
    public final MonitorJobRunLog MONITOR_JOB_RUN_LOG = dev.kamko.jooq_gen.tables.MonitorJobRunLog.MONITOR_JOB_RUN_LOG;

    /**
     * The table <code>public.monitored_article</code>.
     */
    public final MonitoredArticle MONITORED_ARTICLE = dev.kamko.jooq_gen.tables.MonitoredArticle.MONITORED_ARTICLE;

    /**
     * The table <code>public.source</code>.
     */
    public final Source SOURCE = dev.kamko.jooq_gen.tables.Source.SOURCE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ARTICLE_FB_ENGAGEMENT_ID_SEQ,
            Sequences.ARTICLE_ID_SEQ,
            Sequences.MEDIA_ID_SEQ,
            Sequences.MONITOR_JOB_RUN_LOG_ID_SEQ,
            Sequences.MONITORED_ARTICLE_ID_SEQ,
            Sequences.SOURCE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT,
            ArticleMedia.ARTICLE_MEDIA,
            Media.MEDIA,
            MonitorJobRunLog.MONITOR_JOB_RUN_LOG,
            MonitoredArticle.MONITORED_ARTICLE,
            Source.SOURCE);
    }
}
