/*
 * This file is generated by jOOQ.
 */
package dev.kamko.jooq_gen;


import dev.kamko.jooq_gen.tables.Article;
import dev.kamko.jooq_gen.tables.ArticleFbEngagement;
import dev.kamko.jooq_gen.tables.ArticleMedia;
import dev.kamko.jooq_gen.tables.Media;
import dev.kamko.jooq_gen.tables.MonitorJobRunLog;
import dev.kamko.jooq_gen.tables.MonitoredArticle;
import dev.kamko.jooq_gen.tables.Source;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>public.article_fb_engagement</code>.
     */
    public static final ArticleFbEngagement ARTICLE_FB_ENGAGEMENT = ArticleFbEngagement.ARTICLE_FB_ENGAGEMENT;

    /**
     * The table <code>public.article_media</code>.
     */
    public static final ArticleMedia ARTICLE_MEDIA = ArticleMedia.ARTICLE_MEDIA;

    /**
     * The table <code>public.media</code>.
     */
    public static final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>public.monitor_job_run_log</code>.
     */
    public static final MonitorJobRunLog MONITOR_JOB_RUN_LOG = MonitorJobRunLog.MONITOR_JOB_RUN_LOG;

    /**
     * The table <code>public.monitored_article</code>.
     */
    public static final MonitoredArticle MONITORED_ARTICLE = MonitoredArticle.MONITORED_ARTICLE;

    /**
     * The table <code>public.source</code>.
     */
    public static final Source SOURCE = Source.SOURCE;
}
